// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edqboilewejdukyoyrou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcWJvaWxld2VqZHVreW95cm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NTg5OTgsImV4cCI6MjA1NzMzNDk5OH0.PXN3F0-uqW_ApWqnER2yCVabTI1RhWtrwbj6reaSwMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);